"""Hardware-aware profiling via NCU on Modal B200."""

import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from forgeflow.config import (
    COMPUTE_BOUND_THRESHOLD,
    MEMORY_BOUND_THRESHOLD,
    NCU_METRICS,
    PROJECT_ROOT,
    TENSOR_CORE_UTIL_LOW,
)


@dataclass
class ProfileResult:
    sm_throughput_pct: float = 0.0
    dram_throughput_pct: float = 0.0
    l1_lsu_pct: float = 0.0
    tensor_core_pct: float = 0.0
    warp_occupancy_pct: float = 0.0
    bottleneck: str = "unknown"
    recommendations: list[str] | None = None

    def __post_init__(self):
        if self.recommendations is None:
            self.recommendations = []

    def to_dict(self) -> dict:
        return {
            "sm_throughput_pct": self.sm_throughput_pct,
            "dram_throughput_pct": self.dram_throughput_pct,
            "l1_lsu_pct": self.l1_lsu_pct,
            "tensor_core_pct": self.tensor_core_pct,
            "warp_occupancy_pct": self.warp_occupancy_pct,
            "bottleneck": self.bottleneck,
            "recommendations": self.recommendations,
        }


def run_ncu_profile() -> ProfileResult:
    """Run NCU profiling via Modal and parse results.

    Uses flashinfer_bench.agents.flashinfer_bench_run_ncu if available,
    otherwise falls back to parsing modal run output.
    """
    ncu_script = PROJECT_ROOT / "forgeflow" / "_ncu_modal.py"
    _write_ncu_modal_script(ncu_script)

    try:
        result = subprocess.run(
            ["modal", "run", str(ncu_script)],
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            timeout=600,
        )
        output = result.stdout + result.stderr
        return _parse_ncu_output(output)
    except subprocess.TimeoutExpired:
        print("[oracle] NCU profiling timed out")
        return ProfileResult(bottleneck="timeout")
    except Exception as e:
        print(f"[oracle] NCU profiling failed: {e}")
        return ProfileResult(bottleneck="error")


def _write_ncu_modal_script(path: Path) -> None:
    """Generate a temporary Modal script that runs NCU profiling."""
    script_content = '''"""NCU profiling on Modal B200 (auto-generated by ForgeFlow)."""
import sys, json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import modal
from flashinfer_bench import Solution, TraceSet

app = modal.App("forgeflow-ncu")
trace_volume = modal.Volume.from_name("flashinfer-trace", create_if_missing=True)

image = (
    modal.Image.debian_slim(python_version="3.12")
    .pip_install("flashinfer-bench", "torch", "triton", "numpy")
)

@app.function(image=image, gpu="B200:1", timeout=600, volumes={"/data": trace_volume})
def profile_ncu(solution: Solution) -> str:
    from flashinfer_bench import TraceSet
    try:
        from flashinfer_bench.agents import flashinfer_bench_run_ncu
    except ImportError:
        return json.dumps({"error": "flashinfer_bench_run_ncu not available"})

    trace_set = TraceSet.from_path("/data")
    definition_name = solution.definition
    workloads = trace_set.workloads.get(definition_name, [])
    if not workloads:
        return json.dumps({"error": "no workloads found"})

    # Profile on the first (smallest) workload for speed
    workload = workloads[0]
    try:
        output = flashinfer_bench_run_ncu(
            solution=solution,
            workload=workload,
            set="detailed",
            page="details",
            timeout=120,
        )
        return str(output)
    except Exception as e:
        return json.dumps({"error": str(e)})


@app.local_entrypoint()
def main():
    from scripts.pack_solution import pack_solution

    solution_path = pack_solution()
    solution = Solution.model_validate_json(solution_path.read_text())
    result = profile_ncu.remote(solution)
    print("NCU_RESULT_START")
    print(result)
    print("NCU_RESULT_END")
'''
    path.write_text(script_content)


def _parse_ncu_output(output: str) -> ProfileResult:
    """Parse NCU output to extract key metrics."""
    profile = ProfileResult()

    # Try to find structured NCU result block
    ncu_block = ""
    in_block = False
    for line in output.splitlines():
        if "NCU_RESULT_START" in line:
            in_block = True
            continue
        if "NCU_RESULT_END" in line:
            in_block = False
            continue
        if in_block:
            ncu_block += line + "\n"

    # Parse percentage metrics from NCU output
    metric_map = {
        "sm__throughput": "sm_throughput_pct",
        "dram__throughput": "dram_throughput_pct",
        "l1tex__t_sectors_pipe_lsu": "l1_lsu_pct",
        "sm__inst_executed_pipe_tensor": "tensor_core_pct",
        "sm__warps_active": "warp_occupancy_pct",
    }

    text = ncu_block if ncu_block else output
    for metric_prefix, attr in metric_map.items():
        pattern = rf"{re.escape(metric_prefix)}[^\d]*?(\d+\.?\d*)\s*%?"
        match = re.search(pattern, text)
        if match:
            setattr(profile, attr, float(match.group(1)))

    profile.bottleneck = classify_bottleneck(profile)
    profile.recommendations = generate_recommendations(profile)
    return profile


def classify_bottleneck(profile: ProfileResult) -> str:
    """Classify the primary performance bottleneck."""
    sm = profile.sm_throughput_pct
    dram = profile.dram_throughput_pct

    if sm < 20 and dram < 20:
        return "latency-bound"  # neither compute nor memory saturated → launch overhead
    if dram >= MEMORY_BOUND_THRESHOLD and sm < COMPUTE_BOUND_THRESHOLD:
        return "memory-bound"
    if sm >= COMPUTE_BOUND_THRESHOLD and dram < MEMORY_BOUND_THRESHOLD:
        return "compute-bound"
    if sm >= COMPUTE_BOUND_THRESHOLD and dram >= MEMORY_BOUND_THRESHOLD:
        return "balanced"  # both saturated → well optimized or need algorithmic change
    if dram > sm:
        return "memory-bound"
    return "compute-bound"


def generate_recommendations(profile: ProfileResult) -> list[str]:
    """Generate optimization recommendations based on profile data."""
    recs = []
    bottleneck = profile.bottleneck

    if bottleneck == "latency-bound":
        recs.append("CRITICAL: Kernel launch overhead dominates. "
                     "Fuse the 32-expert Python loop into a single grouped-GEMM Triton kernel.")
        recs.append("Reduce kernel launch count by batching token-expert assignments.")

    if bottleneck == "memory-bound":
        recs.append("Fuse FP8 dequantization into GEMM inner loop to avoid materializing float32 weights.")
        recs.append("Use TMA (Tensor Memory Accelerator) for async global→shared memory copies.")
        recs.append("Optimize L2 cache hit rate: sort tokens by expert before GEMM to improve locality.")
        recs.append("Consider keeping intermediate results in shared memory between GEMM1 and GEMM2.")

    if bottleneck == "compute-bound":
        recs.append("Maximize Tensor Core utilization via larger tile sizes (BLOCK_M=128, BLOCK_N=256).")
        recs.append("Use warp-specialized persistent kernels (producer/consumer pattern).")
        recs.append("Ensure tile shapes align with Blackwell's native MMA shapes.")

    if profile.tensor_core_pct < TENSOR_CORE_UTIL_LOW:
        recs.append(f"Tensor Core utilization is only {profile.tensor_core_pct:.1f}%. "
                     "Replace torch.matmul with tl.dot in Triton for direct Tensor Core access.")
        recs.append("Ensure matrix dimensions are multiples of 16 for optimal Tensor Core scheduling.")

    if profile.l1_lsu_pct > 80:
        recs.append("L1/LSU is near saturation. Reduce shared memory bank conflicts "
                     "and use vectorized loads (tl.load with BLOCK_SIZE >= 128).")

    if not recs:
        recs.append("Profile looks balanced. Consider algorithmic improvements: "
                     "SplitK decomposition or persistent kernel approach.")

    return recs


def print_profile_report(profile: ProfileResult) -> None:
    """Pretty-print the profiling report."""
    print(f"\n{'─'*60}")
    print(f"  Hardware Oracle — B200 Profile Report")
    print(f"{'─'*60}")
    print(f"  SM Throughput:    {profile.sm_throughput_pct:6.1f}%")
    print(f"  DRAM Throughput:  {profile.dram_throughput_pct:6.1f}%")
    print(f"  L1/LSU Pressure: {profile.l1_lsu_pct:6.1f}%")
    print(f"  Tensor Core Use: {profile.tensor_core_pct:6.1f}%")
    print(f"  Warp Occupancy:  {profile.warp_occupancy_pct:6.1f}%")
    print(f"  Bottleneck:      {profile.bottleneck.upper()}")
    print(f"{'─'*60}")
    print(f"  Recommendations:")
    for i, rec in enumerate(profile.recommendations or [], 1):
        print(f"    {i}. {rec}")
    print(f"{'─'*60}\n")
